openapi: 3.0.0
info:
  title: API de Instrumentos (Vulnerable)
  version: 1.0.0
  description: Una API de ejemplo para gestión de instrumentos musicales, que incluye endpoints con vulnerabilidades de inyección SQL.

servers:
  - url: http://localhost:8080
    description: Servidor Local de Desarrollo

tags:
  - name: Instrumentos (Vulnerable SQLi)
    description: Operaciones sobre instrumentos con inyección SQL

paths:
  /instruments/vulnerable-sqli:
    delete:
      summary: Elimina instrumentos (Vulnerable a SQL Injection)
      operationId: deleteInstrumentSQLi
      tags:
        - Instrumentos (Vulnerable SQLi)
      parameters:
        - in: query
          name: id
          schema:
            type: string
          required: true
          description: ID del instrumento a eliminar. Campo vulnerable a inyección SQL.
          example: "3' OR ''=''" # Payload de ejemplo para eliminar todos los registros
      responses:
        '200':
          description: Instrumentos eliminados exitosamente.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: boolean
                    example: false
        '400':
          description: ID del instrumento requerido.
        '404':
          description: No se pudo eliminar el instrumento o no se encontró.
        '500':
          description: Error interno del servidor al eliminar el instrumento.

  /instruments/vulnerable-sqligetinst:
    get:
      summary: Obtiene instrumentos por ID (Vulnerable a SQL Injection)
      operationId: getInstrumentByIDSQLi
      tags:
        - Instrumentos (Vulnerable SQLi)
      parameters:
        - in: query
          name: id
          schema:
            type: string
          required: true
          description: ID del instrumento. Campo vulnerable a inyección SQL para extraer múltiples registros.
          example: "3' OR ''=''" # Payload de ejemplo para obtener todos los registros
      responses:
        '200':
          description: Lista de instrumentos recuperados exitosamente (puede incluir todos los registros si hay inyección).
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Instrument' # Referencia al modelo de Instrumento
        '400':
          description: ID del instrumento requerido.
        '404':
          description: Instrumento(s) no encontrado(s) o error de base de datos.
        '500':
          description: Error interno del servidor al consultar la base de datos o al leer los datos.

components:
  schemas:
    Instrument:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: Identificador único del instrumento.
          example: 1
        name:
          type: string
          description: Nombre del instrumento.
          example: "Guitarra eléctrica"
        description:
          type: string
          description: Descripción del instrumento.
          example: "Guitarra Fender Stratocaster de seis cuerdas"
        price:
          type: number
          format: float
          description: Precio del instrumento.
          example: 1200.00
        createdAt:
          type: string
          format: date-time
          description: Fecha y hora de creación del registro.
          example: "2025-06-19T04:34:03.760094Z"
        updatedAt:
          type: string
          format: date-time
          description: Fecha y hora de la última actualización del registro.
          example: "2025-06-19T04:34:03.760094Z"